function gameTutorial() 
% Show the game instructions using msgbox
   msgbox(sprintf([...
         'Try to make your snake as long as possible by directing them to eat the food.\n\n'...
         'There are 3 different game modes with 4 different levels (1-4) to choose.\n'...
         'To play the game, you should first choose your preferred game mode and level, then click File/New Game or Ctrl+ N to start the game.\n\n'...
         'The higher the chosen level is, the faster the snake move, but also the more points you receive.']))
end